import Head from "next/head";
import { useState, useReducer, useRef } from "react";
import useLocation from "@/hooks/use-location";
import TheMap from "@/components/TheMap";
import { useJsApiLoader } from "@react-google-maps/api";
import TripForm from "@/components/TripForm";
import { TripReducers, initialState } from "@/reducers/trip.reducers";
import currentTrip from "@/context/trip.context";

const libraries = ["places"];

export default function Home() {
  const [loadedMap, setLoadedMap] = useState(null);
  const [currentStep, setCurrentStep] = useState(0);
  const [nextStep, setNextStep] = useState(null);

  const originRef = useRef();
  const destinationRef = useRef();

  const [trip, dispatchTrip] = useReducer(TripReducers, initialState);

  const { currentPosition } = useLocation();

  const { isLoaded } = useJsApiLoader({
    id: "google-map-script",
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_KEY,
    libraries,
  });

  return (
    <>
      <Head>
        <title>GO - carpool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <currentTrip.Provider
        value={{
          trip,
          dispatchTrip,
          loadedMap,
          currentPosition,
          originRef,
          destinationRef,
          setCurrentStep,
          setNextStep,
          currentStep,
          nextStep,
        }}
      >
        {currentPosition && isLoaded ? (
          <>
            <TripForm />
            <TheMap setLoadedMap={setLoadedMap} />
            {/* {navigation box here} */}
          </>
        ) : (
          <p>Loading...</p>
        )}
      </currentTrip.Provider>
    </>
  );
}
