import Head from "next/head";
import { useState } from "react";
import useLocation from "@/hooks/use-location";
import TheMap from "@/components/TheMap";
import { useJsApiLoader } from "@react-google-maps/api";
import TripForm from "@/components/TripForm";

const libraries = ["places"];

export default function Home() {
  const [loadedMap, setLoadedMap] = useState(null);

  const { currentPosition } = useLocation();

  const { isLoaded } = useJsApiLoader({
    id: "google-map-script",
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_KEY,
    libraries,
  });

  return (
    <>
      <Head>
        <title>GO - carpool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {currentPosition && <TripForm />}
      {isLoaded ? (
        <TheMap currentPosition={currentPosition} setLoadedMap={setLoadedMap} />
      ) : (
        <p>Loading...</p>
      )}
      {/* {navigation box here} */}
    </>
  );
}
